# Generated by Django 4.2.4 on 2024-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_assigned_judges_eventjudges'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='event_images/'),
            preserve_default=False,
        ),
    ]
